using '../02-main.bicep'
param location = 'eastus2'
param workloadName = 'bicplus'
param environmentSuffix = 'loc'
param vnetName = 'bicplus-loc-vnet'
param webSubnetName = 'web-app-subnet'
param servicesSubnetName = 'services-subnet'
param appGatewaySubnetName = 'app-gw-subnet'
param enableZoneRedundancy = false
param appServicePlanSku = 'S1'
param logAnalyticsWorkspaceName = 'bicplus-loc-laws'
param keyVaultName = 'bicplus-loc-kv'
